class ListStates:
    START_TEST = 0
    INIT_TEST = 10
    WAIT_FOR_SN = 20
    SN_OK = 30
    SN_NOK = 40
    START_STREAM_CAMERA = 50
    STOP_STREAM_CAMERA = 60
    SAVE_TO_DB = 70
    SHOW_STATUS = 80
